services:
  - type: web
    name: event-management-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: DEBUG
        value: "False"
